### ISSUE TITLE
heroku error

### ISSUE THREAD

**Issue by DESTROYER-32** [SpEcHiDe/AnyDLBot#10]
019-05-16T13:26:39.676414+00:00 app[worker.1]: Traceback (most recent call last):
2019-05-16T13:26:39.676440+00:00 app[worker.1]:   File "bot.py", line 15, in <module>
2019-05-16T13:26:39.676541+00:00 app[worker.1]:     from sample_config import Config
2019-05-16T13:26:39.676546+00:00 app[worker.1]:   File "/app/sample_config.py", line 3, in <module>
2019-05-16T13:26:39.676646+00:00 app[worker.1]:     class Config(object):
2019-05-16T13:26:39.676651+00:00 app[worker.1]:   File "/app/sample_config.py", line 28, in Config
2019-05-16T13:26:39.676758+00:00 app[worker.1]:     CHUNK_SIZE = int(os.environ.get("CHUNK_SIZE", 128))
2019-05-16T13:26:39.676766+00:00 app[worker.1]: ValueError: invalid literal for int() with base 10: ''

**Comment by SpEcHiDe** [comment]
You filled an empty string for CHUNK_SIZE while deploying to Heroku. 
This is not an issue with my code. Sorry to disappoint you. 
N.B.: https://spechide.shrimadhavuk.me/in.timelinestudios.ochaim/file.php?f=AwADBAADwwMAAq0pGVImBp0hpP_SDQI

**Comment by R3DLIZ4RD** [comment]
Subscribe @MalayalamTrollVoice

**Comment by R3DLIZ4RD** [comment]
Subscribe @MalayalamTrollVoice
