### ISSUE TITLE
bot not responding to links

### ISSUE THREAD

**Issue by ShubhamPandeyy** [SpEcHiDe/AnyDLBot#18]
**Bot Responds** To **Normal Commands** Like /Start or /me but when it comes to _links_, (I had tried various links, it gives error on all of them) it **doesn't responds** and when I check the _log_, it shows me this

Here is the log:
`2019-07-29T18:06:25.956871+00:00 app[worker.1]: 2019-07-29 18:06:25,956 - plugins._core - INFO - ['youtube-dl', '--no-warnings', '--youtube-skip-dash-manifest', '-j', 'https://vipkhan.mobi/cache/CAT_punjabi-videos/CAT_punjabi-video-song/4375/mp4/mp4-1080p/Ja%20Ve%20Ja%20Parmish%20Verma%20G%20Sidhu%20-%20HDYaar.Com.mp4']
2019-07-29T18:06:29.397964+00:00 app[worker.1]: 2019-07-29 18:06:29,397 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): placehold.it:443
2019-07-29T18:06:29.571628+00:00 app[worker.1]: 2019-07-29 18:06:29,570 - urllib3.connectionpool - DEBUG - https://placehold.it:443 "GET /90x90 HTTP/1.1" 200 276
2019-07-29T18:06:29.614825+00:00 app[worker.1]: 2019-07-29 18:06:29,600 - pyrogram.client.ext.dispatcher - ERROR - module 'pyrogram' has no attribute 'ParseMode'
2019-07-29T18:06:29.614871+00:00 app[worker.1]: Traceback (most recent call last):
2019-07-29T18:06:29.615124+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/pyrogram/client/ext/dispatcher.py", line 180, in update_worker
2019-07-29T18:06:29.615128+00:00 app[worker.1]:     handler.callback(self.client, *args)
2019-07-29T18:06:29.615131+00:00 app[worker.1]:   File "/app/plugins/_core.py", line 223, in echo
2019-07-29T18:06:29.615133+00:00 app[worker.1]:     parse_mode=pyrogram.ParseMode.HTML,
2019-07-29T18:06:29.615201+00:00 app[worker.1]: AttributeError: module 'pyrogram' has no attribute 'ParseMode'`

Also,
It asks me to upgrade my subscription even when I'm the auth user.

Kindly Look Into This

**Comment by ShubhamPandeyy** [comment]
Even after the fix, its not responding to links

Here is the log
`2019-08-03T16:54:57.787540+00:00 app[worker.1]: 2019-08-03 16:54:57,787 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): chatbase.com:443
2019-08-03T16:54:58.032648+00:00 app[worker.1]: 2019-08-03 16:54:58,032 - urllib3.connectionpool - DEBUG - https://chatbase.com:443 "POST /api/message HTTP/1.1" 200 44
2019-08-03T16:55:03.976558+00:00 app[worker.1]: 2019-08-03 16:55:03,976 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): chatbase.com:443
2019-08-03T16:55:04.171331+00:00 app[worker.1]: 2019-08-03 16:55:04,171 - urllib3.connectionpool - DEBUG - https://chatbase.com:443 "POST /api/message HTTP/1.1" 200 44
2019-08-03T16:55:15.005610+00:00 app[worker.1]: 2019-08-03 16:55:15,005 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): chatbase.com:443
2019-08-03T16:55:15.230893+00:00 app[worker.1]: 2019-08-03 16:55:15,230 - urllib3.connectionpool - DEBUG - https://chatbase.com:443 "POST /api/message HTTP/1.1" 200 44
2019-08-03T16:55:15.233758+00:00 app[worker.1]: 2019-08-03 16:55:15,233 - plugins._core - INFO - {
2019-08-03T16:55:15.233761+00:00 app[worker.1]:     "_": "pyrogram.User",
2019-08-03T16:55:15.233763+00:00 app[worker.1]:     "id": 682265727,
2019-08-03T16:55:15.233764+00:00 app[worker.1]:     "is_self": false,
2019-08-03T16:55:15.233766+00:00 app[worker.1]:     "is_contact": false,
2019-08-03T16:55:15.233767+00:00 app[worker.1]:     "is_mutual_contact": false,
2019-08-03T16:55:15.233769+00:00 app[worker.1]:     "is_deleted": false,
2019-08-03T16:55:15.233770+00:00 app[worker.1]:     "is_bot": false,
2019-08-03T16:55:15.233772+00:00 app[worker.1]:     "is_verified": false,
2019-08-03T16:55:15.233775+00:00 app[worker.1]:     "is_restricted": false,
2019-08-03T16:55:15.233777+00:00 app[worker.1]:     "is_scam": false,
2019-08-03T16:55:15.233778+00:00 app[worker.1]:     "is_support": false,
2019-08-03T16:55:15.233780+00:00 app[worker.1]:     "first_name": "ShatteredStar💫",
2019-08-03T16:55:15.233782+00:00 app[worker.1]:     "status": {
2019-08-03T16:55:15.233783+00:00 app[worker.1]:         "_": "pyrogram.UserStatus",
2019-08-03T16:55:15.233784+00:00 app[worker.1]:         "user_id": 682265727,
2019-08-03T16:55:15.233786+00:00 app[worker.1]:         "recently": true
2019-08-03T16:55:15.233787+00:00 app[worker.1]:     },
2019-08-03T16:55:15.233789+00:00 app[worker.1]:     "username": "shubhampandeyy",
2019-08-03T16:55:15.233790+00:00 app[worker.1]:     "language_code": "en",
2019-08-03T16:55:15.233791+00:00 app[worker.1]:     "photo": {
2019-08-03T16:55:15.233793+00:00 app[worker.1]:         "_": "pyrogram.ChatPhoto",
2019-08-03T16:55:15.233794+00:00 app[worker.1]:         "small_file_id": "AQADBQADf4yqKAAEcrj5MgAECA0BAAIC",
2019-08-03T16:55:15.233796+00:00 app[worker.1]:         "big_file_id": "AQADBQADf4yqKAAEcrj5MgAECg0BAAEBAg"
2019-08-03T16:55:15.233797+00:00 app[worker.1]:     }
2019-08-03T16:55:15.233799+00:00 app[worker.1]: }
2019-08-03T16:55:15.233942+00:00 app[worker.1]: 2019-08-03 16:55:15,233 - plugins._core - INFO - ['youtube-dl', '--no-warnings', '--youtube-skip-dash-manifest', '-j', 'https://tor.checker.in/dl/649250048/Avengers.Endgame.2019.720p.WEB_DL.2CH.sample.mkv']
2019-08-03T16:55:17.530002+00:00 app[worker.1]: 2019-08-03 16:55:17,529 - pyrogram.client.ext.dispatcher - ERROR - Invalid URL '': No schema supplied. Perhaps you meant http://?
2019-08-03T16:55:17.530015+00:00 app[worker.1]: Traceback (most recent call last):
2019-08-03T16:55:17.530017+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/pyrogram/client/ext/dispatcher.py", line 183, in update_worker
2019-08-03T16:55:17.530019+00:00 app[worker.1]:     await handler.callback(self.client, *args)
2019-08-03T16:55:17.530021+00:00 app[worker.1]:   File "/app/plugins/_core.py", line 217, in echo
2019-08-03T16:55:17.530024+00:00 app[worker.1]:     update.chat.id
2019-08-03T16:55:17.530026+00:00 app[worker.1]:   File "/app/helper_funcs/help_uploadbot.py", line 23, in DownLoadFile
2019-08-03T16:55:17.530028+00:00 app[worker.1]:     r = requests.get(url, allow_redirects=True, stream=True)
2019-08-03T16:55:17.530030+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/requests/api.py", line 75, in get
2019-08-03T16:55:17.530032+00:00 app[worker.1]:     return request('get', url, params=params, **kwargs)
2019-08-03T16:55:17.530034+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/requests/api.py", line 60, in request
2019-08-03T16:55:17.530036+00:00 app[worker.1]:     return session.request(method=method, url=url, **kwargs)
2019-08-03T16:55:17.530038+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/requests/sessions.py", line 519, in request
2019-08-03T16:55:17.530040+00:00 app[worker.1]:     prep = self.prepare_request(req)
2019-08-03T16:55:17.530042+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/requests/sessions.py", line 462, in prepare_request
2019-08-03T16:55:17.530043+00:00 app[worker.1]:     hooks=merge_hooks(request.hooks, self.hooks),
2019-08-03T16:55:17.530045+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/requests/models.py", line 313, in prepare
2019-08-03T16:55:17.530047+00:00 app[worker.1]:     self.prepare_url(url, params)
2019-08-03T16:55:17.530049+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/requests/models.py", line 387, in prepare_url
2019-08-03T16:55:17.530051+00:00 app[worker.1]:     raise MissingSchema(error)
2019-08-03T16:55:17.530053+00:00 app[worker.1]: requests.exceptions.MissingSchema: Invalid URL '': No schema supplied. Perhaps you meant http://?`

**Comment by SpEcHiDe** [comment]
type the URL correctly in the message box, without special characters.
