### ISSUE TITLE
Freezes with trying to download message

### ISSUE THREAD

**Issue by IamJithendra** [SpEcHiDe/AnyDLBot#33]
2019-10-21T07:29:34.098311+00:00 app[worker.1]: 2019-10-21 07:29:34,092 - pyrogram.client.ext.dispatcher - ERROR - module 'asyncio' has no attribute 'TimeOutError'
2019-10-21T07:29:34.098333+00:00 app[worker.1]: Traceback (most recent call last):
2019-10-21T07:29:34.098337+00:00 app[worker.1]:   File "/app/plugins/dl_button.py", line 99, in ddl_call_back
2019-10-21T07:29:34.09834+00:00 app[worker.1]:     c_time
2019-10-21T07:29:34.098344+00:00 app[worker.1]:   File "/app/plugins/dl_button.py", line 264, in download_coroutine
2019-10-21T07:29:34.098346+00:00 app[worker.1]:     total_length = int(response.headers["Content-Length"])
2019-10-21T07:29:34.098348+00:00 app[worker.1]:   File "multidict/_multidict.pyx", line 62, in multidict._multidict._Base.__getitem__
2019-10-21T07:29:34.09835+00:00 app[worker.1]:   File "multidict/_multidict.pyx", line 57, in multidict._multidict._Base._getone
2019-10-21T07:29:34.098352+00:00 app[worker.1]:   File "multidict/_multidict.pyx", line 52, in multidict._multidict._Base._getone
2019-10-21T07:29:34.098356+00:00 app[worker.1]: KeyError: 'Content-Length'
2019-10-21T07:29:34.098358+00:00 app[worker.1]: 
2019-10-21T07:29:34.09836+00:00 app[worker.1]: During handling of the above exception, another exception occurred:
2019-10-21T07:29:34.098361+00:00 app[worker.1]: 
2019-10-21T07:29:34.098363+00:00 app[worker.1]: Traceback (most recent call last):
2019-10-21T07:29:34.098366+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/pyrogram/client/ext/dispatcher.py", line 198, in update_worker
2019-10-21T07:29:34.098368+00:00 app[worker.1]:     await handler.callback(self.client, *args)
2019-10-21T07:29:34.09837+00:00 app[worker.1]:   File "/app/plugins/cb_buttons.py", line 135, in button
2019-10-21T07:29:34.098371+00:00 app[worker.1]:     await ddl_call_back(bot, update)
2019-10-21T07:29:34.098374+00:00 app[worker.1]:   File "/app/plugins/dl_button.py", line 101, in ddl_call_back
2019-10-21T07:29:34.098376+00:00 app[worker.1]:     except asyncio.TimeOutError:
2019-10-21T07:29:34.098378+00:00 app[worker.1]: AttributeError: module 'asyncio' has no attribute 'TimeOutError'
2019-10-21T07:29:34.10294+00:00 app[worker.1]: 2019-10-21 07:29:34,102 - asyncio - ERROR - SSL error in data received
2019-10-21T07:29:34.102943+00:00 app[worker.1]: protocol: <asyncio.sslproto.SSLProtocol object at 0x7f6e2ede1358>
2019-10-21T07:29:34.102946+00:00 app[worker.1]: transport: <_SelectorSocketTransport fd=13 read=polling write=<idle, bufsize=0>>
2019-10-21T07:29:34.102948+00:00 app[worker.1]: Traceback (most recent call last):
2019-10-21T07:29:34.10295+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
2019-10-21T07:29:34.102952+00:00 app[worker.1]:     ssldata, appdata = self._sslpipe.feed_ssldata(data)
2019-10-21T07:29:34.102955+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.7/asyncio/sslproto.py", line 207, in feed_ssldata
2019-10-21T07:29:34.102957+00:00 app[worker.1]:     self._sslobj.unwrap()
2019-10-21T07:29:34.102959+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.7/ssl.py", line 767, in unwrap
2019-10-21T07:29:34.102961+00:00 app[worker.1]:     return self._sslobj.shutdown()
2019-10-21T07:29:34.102963+00:00 app[worker.1]: ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2605)

**Comment by IamJithendra** [comment]
@SpEcHiDe  what is the issue here ?
