### ISSUE TITLE
youtube_dl_echo.py returning incorrect formats 

### ISSUE THREAD

**Issue by m4mallu** [SpEcHiDe/AnyDLBot#77]
All are fine. but when selecting the required format, the following errors occurs . Plz fix..

```
await handler.callback(self.client, *args)
File "/app/plugins/cb_buttons.py", line 38, in button
await youtube_dl_call_back(bot, update)
File "/app/plugins/youtube_dl_button.py", line 182, in youtube_dl_call_back
download_directory_contents = os.path.listdir(download_directory_dirname)
AttributeError: module 'posixpath' has no attribute 'listdir'
```

**Comment by SpEcHiDe** [comment]
can you share full traceback? and also the ENV var of DOWNLOAD_LOCATION, that you have filled?

**Comment by m4mallu** [comment]
```
2020-06-07T07:57:12.623882+00:00 app[worker.1]: 2020-06-07 07:57:12,623 - root - INFO - Started 4 UpdatesWorkerTasks

2020-06-07T07:57:12.624227+00:00 app[worker.1]: 2020-06-07 07:57:12,624 - root - INFO - Started 4 DownloadWorkerTasks

2020-06-07T07:57:12.624481+00:00 app[worker.1]: 2020-06-07 07:57:12,624 - root - INFO - Started 4 UpdateWorkerTasks

2020-06-07T07:57:47.919037+00:00 app[worker.1]: 2020-06-07 07:57:47,918 - plugins.youtube_dl_echo - INFO - {

2020-06-07T07:57:47.919047+00:00 app[worker.1]:     "_": "pyrogram.User",

2020-06-07T07:57:47.919048+00:00 app[worker.1]:     "id": xxxxxxxxxx,

2020-06-07T07:57:47.919048+00:00 app[worker.1]:     "is_self": false,

2020-06-07T07:57:47.919048+00:00 app[worker.1]:     "is_contact": false,

2020-06-07T07:57:47.919049+00:00 app[worker.1]:     "is_mutual_contact": false,

2020-06-07T07:57:47.919049+00:00 app[worker.1]:     "is_deleted": false,

2020-06-07T07:57:47.919050+00:00 app[worker.1]:     "is_bot": false,

2020-06-07T07:57:47.919050+00:00 app[worker.1]:     "is_verified": false,

2020-06-07T07:57:47.919050+00:00 app[worker.1]:     "is_restricted": false,

2020-06-07T07:57:47.919051+00:00 app[worker.1]:     "is_scam": false,

2020-06-07T07:57:47.919051+00:00 app[worker.1]:     "is_support": false,

2020-06-07T07:57:47.919052+00:00 app[worker.1]:     "first_name": "xxxxxxxx",

2020-06-07T07:57:47.919052+00:00 app[worker.1]:     "status": "recently",

2020-06-07T07:57:47.919053+00:00 app[worker.1]:     "username": "xxxxxxxxx",

2020-06-07T07:57:47.919053+00:00 app[worker.1]:     "language_code": "en",

2020-06-07T07:57:47.919053+00:00 app[worker.1]:     "dc_id": 5,

2020-06-07T07:57:47.919054+00:00 app[worker.1]:     "photo": {

2020-06-07T07:57:47.919054+00:00 app[worker.1]:         "_": "pyrogram.ChatPhoto",

2020-06-07T07:57:47.919056+00:00 app[worker.1]:     }

2020-06-07T07:57:47.919056+00:00 app[worker.1]: }

2020-06-07T07:57:50.938526+00:00 app[worker.1]: 2020-06-07 07:57:50,938 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): i.ytimg.com:443

2020-06-07T07:57:50.966326+00:00 app[worker.1]: 2020-06-07 07:57:50,966 - urllib3.connectionpool - DEBUG - https://i.ytimg.com:443 "GET /vi/CPQKM2YJfnw/hqdefault.jpg HTTP/1.1" 200 28401

2020-06-07T07:57:51.124294+00:00 app[worker.1]: 2020-06-07 07:57:51,124 - root - INFO - NetWorkerTask started

2020-06-07T07:58:00.277172+00:00 app[worker.1]: 2020-06-07 07:58:00,276 - plugins.youtube_dl_button - INFO - ['youtube-dl', '-c', '--max-filesize', '1572864000', '--embed-subs', '-f', '250+bestaudio', '--hls-prefer-ffmpeg', 'https://youtu.be/CPQKM2YJfnw', '-o', './DOWNLOADS/1158349660/BAD Salsa: Indias Got Talent Winner Dance Duo SHOCK The Judges With HOT Fast Energetic Act_250.webm', '--proxy', '', '--no-warnings']

2020-06-07T07:58:02.716485+00:00 app[worker.1]: 2020-06-07 07:58:02,716 - plugins.youtube_dl_button - INFO - ERROR: The first format must contain the video, try using "-f 140+250"

2020-06-07T07:58:02.716597+00:00 app[worker.1]: 2020-06-07 07:58:02,716 - plugins.youtube_dl_button - INFO - [youtube] CPQKM2YJfnw: Downloading webpage

2020-06-07T07:58:02.717907+00:00 app[worker.1]: 2020-06-07 07:58:02,716 - pyrogram.client.ext.dispatcher - ERROR - module 'posixpath' has no attribute 'listdir'

2020-06-07T07:58:02.717908+00:00 app[worker.1]: Traceback (most recent call last):

2020-06-07T07:58:02.717909+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/pyrogram/client/ext/dispatcher.py", line 204, in update_worker

2020-06-07T07:58:02.717909+00:00 app[worker.1]:     await handler.callback(self.client, *args)

2020-06-07T07:58:02.717910+00:00 app[worker.1]:   File "/app/plugins/cb_buttons.py", line 38, in button

2020-06-07T07:58:02.717910+00:00 app[worker.1]:     await youtube_dl_call_back(bot, update)

2020-06-07T07:58:02.717911+00:00 app[worker.1]:   File "/app/plugins/youtube_dl_button.py", line 182, in youtube_dl_call_back

2020-06-07T07:58:02.717911+00:00 app[worker.1]:     download_directory_contents = os.path.listdir(download_directory_dirname)

2020-06-07T07:58:02.717912+00:00 app[worker.1]: AttributeError: module 'posixpath' has no attribute 'listdir'


```

**Comment by SpEcHiDe** [comment]
ERROR: The first format must contain the video, try using "-f 140+250"
This happens when our wrapper is trying to take a wrong format.

For now, Please select any other format except the below four formats.
![select-area_20200607134817](https://user-images.githubusercontent.com/6317196/83963722-aba59280-a8c5-11ea-8c8b-4e8d602eec88.png)

**Comment by m4mallu** [comment]
Tried with a different file nd format, but the case persist !
